name: tmexpress
description: An app for delivering goods from China

# Run flutter pub upgrade --major-versions to upgrade all dependencies

publish_to: 'none'

version: 0.0.2+2

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # L10n
  intl_utils: ^2.7.0

  # State management
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0

  # DI
  get_it: ^7.2.0
  injectable: ^1.4.1

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0


  # UI
  flutter_svg: ^1.1.1+1
  flash: ^2.0.3+3
  url_launcher: ^6.1.5
  infinite_scroll_pagination: ^3.2.0
  cached_network_image: ^3.2.1
  blurhash_dart: ^1.1.0
  carousel_slider: ^4.1.1
  lottie: ^1.3.0
  mask_text_input_formatter: ^2.3.0
  share_plus: ^4.0.10
  menu_button: ^1.4.2+1
  introduction_screen: ^3.0.2
  
  # Network
  built_value: ^8.4.0
  dio: ^4.0.6
  dio_cache_interceptor_hive_store: ^3.2.0
  json_annotation: ^4.6.0
  retrofit: ^3.3.1

  # Misc
  dartz: ^0.10.1
  analyzer: ^4.3.0
  package_info: ^2.0.2
  win32: ^2.6.1

  # Firebase
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_dynamic_links: ^5.0.6
  firebase_messaging: ^14.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generators
  build_runner: ^2.2.0
  injectable_generator: ^1.5.4
  retrofit_generator: ^4.2.0
  json_serializable: ^6.3.1
  built_value_generator: ^8.4.0

  # UI
  flutter_native_splash: ^2.2.5
  flutter_launcher_icons: ^0.9.3
  device_preview: ^1.1.0

  # Linting
  flutter_lints: ^2.0.1
  fwfh_text_style: ^2.22.8+1


  # Network
  alice: ^0.2.5
  logger: ^1.1.0

flutter:
  generate: false
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/illustrations/
    - assets/icons/
    - assets/icons/order_statuses/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 900

flutter_intl: 
  enabled: true
  class_name: S
  main_locale: tr
  arb_dir: lib/app/l10n
  output_dir: lib/app/generated

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/launcher_icon_android.png"