name: tmexpress
description: An app for delivering goods from China

# Run flutter pub upgrade --major-versions to upgrade all dependencies

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # L10n
  intl_utils: ^2.4.0

  # State management
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0

  # DI
  get_it: ^7.2.0
  injectable: ^1.4.1

  # Local storage
  shared_preferences: ^2.0.6

  # UI
  flutter_svg: ^1.0.0
  flash: ^2.0.1
  url_launcher: ^6.0.9
  infinite_scroll_pagination: ^3.1.0
  cached_network_image: ^3.1.0
  blurhash_dart: ^1.0.2
  carousel_slider: ^4.0.0
  lottie: ^1.2.1
  
  # Network
  built_value: ^8.0.6
  dio: ^4.0.0
  json_annotation: ^4.0.1
  retrofit: ^3.0.0

  # Misc
  dartz: ^0.10.0
  analyzer: ^2.8.0
  package_info: ^2.0.2

  # Firebase
  firebase_core: ^1.10.0
  firebase_analytics: ^9.0.3
  firebase_crashlytics: ^2.3.0
  firebase_remote_config: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generators
  build_runner: ^2.0.4
  injectable_generator: ^1.4.1
  retrofit_generator: ^3.0.0+2
  json_serializable: ^6.1.1
  built_value_generator: ^8.0.6

  # UI
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.0
  device_preview: ^1.0.0

  # Linting
  flutter_lints: ^1.0.4

  # Network
  alice: ^0.2.4
  logger: ^1.1.0

flutter:
  generate: false
  uses-material-design: true
  
  assets:
    - assets/animations/
  #   - assets/icons/
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700

flutter_intl: 
  enabled: true
  class_name: S
  main_locale: ru
  arb_dir: lib/app/l10n
  output_dir: lib/app/generated

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"