enum AppErrorType {
  unknownError,
  somethingWentWrong,
  serverIsNotAvailable,
  connectionTimeout,
  connectionError,
  apiResponseParsingError,
  badRequest,
  accessTokenError,
  forbidden,
  resourceNotFound,
  methodNotAllowed,
  internalServerError,
  badGateway,
}
