// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdWwv_R5kSLtGqRAEJxHt8cnceoVv20XA',
    appId: '1:18693864465:web:f85fa3c596128f9ff145b0',
    messagingSenderId: '18693864465',
    projectId: 'yakyn-yol',
    authDomain: 'yakyn-yol.firebaseapp.com',
    storageBucket: 'yakyn-yol.appspot.com',
    measurementId: 'G-9MTPS0RS1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4kFAOpnF0r9q7G__Dj9sicaV-V_xW2VU',
    appId: '1:18693864465:android:9fe59d71c2abfae8f145b0',
    messagingSenderId: '18693864465',
    projectId: 'yakyn-yol',
    storageBucket: 'yakyn-yol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIEtERiTBfVWlKTkkCiYFRNvt2sDQhi8o',
    appId: '1:18693864465:ios:3503b9b34bc284bdf145b0',
    messagingSenderId: '18693864465',
    projectId: 'yakyn-yol',
    storageBucket: 'yakyn-yol.appspot.com',
    iosBundleId: 'com.yakynyol.app',
  );
}
