// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgnSQquIfVen0J7rGQXSgQ765Vxs3Q9Ts',
    appId: '1:759685704506:android:712bdb73d53882e0effe03',
    messagingSenderId: '759685704506',
    projectId: 'flutter-template-appcraft',
    storageBucket: 'flutter-template-appcraft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd-MBMiAXzRjVVVal2JXI-zY5uXDgQ140',
    appId: '1:759685704506:ios:4780c0a64a09de0ceffe03',
    messagingSenderId: '759685704506',
    projectId: 'flutter-template-appcraft',
    storageBucket: 'flutter-template-appcraft.appspot.com',
    iosClientId: '759685704506-f9q3jhtas7ve72ft2rd7d5lf16mktobj.apps.googleusercontent.com',
    iosBundleId: 'pro.appcraft.templateflutter',
  );
}
